/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Clases.Cantidad_Mascotas_Por_Cliente;
import Clases.Cliente;
import Clases.Mascota;
import Clases.Pago;
import Clases.Plan;
import Controller.CtlCliente;
import Controller.CtlMascota;
import Controller.CtlPago;
import Controller.CtlPlan;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author 57301
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FormCliente() {
        initComponents();
        ActualizarListaCliente();
        ActualizarListaMascota();
        ActualizarListaPlan();
        ActualizarListaPago();
        actualizarReporte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdentificacionCliente = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonCrearCliente = new javax.swing.JButton();
        jButtonModificarCiente = new javax.swing.JButton();
        jButtonEliminarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCodigo_mascota = new javax.swing.JTextField();
        jTextFieldNombre_Mascota = new javax.swing.JTextField();
        jTextFieldEdad_Mascota = new javax.swing.JTextField();
        jTextFieldPeso_Mascota = new javax.swing.JTextField();
        jTextFieldEspecie = new javax.swing.JTextField();
        jTextField_mascota_Identificacion_Cliente = new javax.swing.JTextField();
        Crear_mascota = new javax.swing.JButton();
        modificar_mascota = new javax.swing.JButton();
        Btt_Eliminar_Mascota = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMascota = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCodigo_plan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNombre_plan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldDescripcion_plan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPrecio_plan = new javax.swing.JTextField();
        Crear_Plan = new javax.swing.JButton();
        Modificar_Plan = new javax.swing.JButton();
        Eliminar_Plan = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePlan = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldCodigo_pago = new javax.swing.JTextField();
        jTextField1Abono = new javax.swing.JTextField();
        jTextFieldSaldo = new javax.swing.JTextField();
        jTextFieldCtd_cuotas = new javax.swing.JTextField();
        jTextFieldFecha_pago = new javax.swing.JTextField();
        jTextFieldAfiliacion = new javax.swing.JTextField();
        jTextField_pago_codMascota = new javax.swing.JTextField();
        jTextField_pago_codPlan = new javax.swing.JTextField();
        Crear_pago = new javax.swing.JButton();
        Modificar_pago = new javax.swing.JButton();
        Eliminar_pago = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePago = new javax.swing.JTable();
        jPanelReporte = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Identificacion Cliente");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Direccion");

        jLabel5.setText("Telefono");

        jTextFieldIdentificacionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacionClienteActionPerformed(evt);
            }
        });

        jTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosActionPerformed(evt);
            }
        });

        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });

        jButtonCrearCliente.setText("Crear Cliente");
        jButtonCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearClienteActionPerformed(evt);
            }
        });

        jButtonModificarCiente.setText("Modificar Cliente");
        jButtonModificarCiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCienteActionPerformed(evt);
            }
        });

        jButtonEliminarCliente.setText("Eliminar Cliente");
        jButtonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCrearCliente)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelefono)
                            .addComponent(jTextFieldIdentificacionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldApellidos)
                            .addComponent(jTextFieldDireccion))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButtonModificarCiente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButtonEliminarCliente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIdentificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearCliente)
                    .addComponent(jButtonModificarCiente))
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarCliente)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edicion Cliente", jPanel1);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista Cliente", jPanel2);

        jLabel6.setText("Codigo Mascota");

        jLabel7.setText("Nombre Mascota");

        jLabel8.setText("Edad Mascota");

        jLabel9.setText("Peso Mascota");

        jLabel10.setText("Especie");

        jLabel11.setText("Identificacion Cliente (Dueño)");

        jTextFieldCodigo_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigo_mascotaActionPerformed(evt);
            }
        });

        jTextFieldNombre_Mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombre_MascotaActionPerformed(evt);
            }
        });

        Crear_mascota.setText("Crear Mascota");
        Crear_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_mascotaActionPerformed(evt);
            }
        });

        modificar_mascota.setText("Modificar Mascota");
        modificar_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_mascotaActionPerformed(evt);
            }
        });

        Btt_Eliminar_Mascota.setText("Eliminar Mascota");
        Btt_Eliminar_Mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_Eliminar_MascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCodigo_mascota)
                    .addComponent(jTextFieldNombre_Mascota)
                    .addComponent(jTextFieldEdad_Mascota)
                    .addComponent(jTextFieldPeso_Mascota)
                    .addComponent(jTextFieldEspecie)
                    .addComponent(jTextField_mascota_Identificacion_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(298, 298, 298))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Crear_mascota)
                        .addGap(47, 47, 47)
                        .addComponent(modificar_mascota))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(Btt_Eliminar_Mascota)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo_mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre_Mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEdad_Mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPeso_Mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_mascota_Identificacion_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crear_mascota)
                    .addComponent(modificar_mascota))
                .addGap(28, 28, 28)
                .addComponent(Btt_Eliminar_Mascota)
                .addGap(139, 139, 139))
        );

        jTabbedPane1.addTab("Edicion Mascota", jPanel3);

        jTableMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableMascota);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Lista Mascota ", jPanel4);

        jLabel12.setText("Codigo Plan");

        jLabel13.setText("Nombre Plan");

        jLabel14.setText("Descripción Plan");

        jTextFieldDescripcion_plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcion_planActionPerformed(evt);
            }
        });

        jLabel15.setText("Precio Plan");

        Crear_Plan.setText("Crear Plan");
        Crear_Plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_PlanActionPerformed(evt);
            }
        });

        Modificar_Plan.setText("Modificar Plan");
        Modificar_Plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_PlanActionPerformed(evt);
            }
        });

        Eliminar_Plan.setText("Eliminar Plan");
        Eliminar_Plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_PlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCodigo_plan, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre_plan)
                            .addComponent(jTextFieldDescripcion_plan)
                            .addComponent(jTextFieldPrecio_plan)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Crear_Plan)
                        .addGap(43, 43, 43)
                        .addComponent(Modificar_Plan))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(Eliminar_Plan)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldCodigo_plan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addComponent(jTextFieldNombre_plan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldDescripcion_plan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldPrecio_plan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crear_Plan)
                    .addComponent(Modificar_Plan))
                .addGap(27, 27, 27)
                .addComponent(Eliminar_Plan)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edicion Plan", jPanel5);

        jTablePlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablePlan);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Lista Plan", jPanel6);

        jLabel16.setText("Codigo Pago");

        jLabel17.setText("Abono");

        jLabel18.setText("Saldo");

        jLabel19.setText("Cantidad de Cuotas");

        jLabel20.setText("Fecha de Pago");

        jLabel21.setText("Plan Afiliacion");

        jLabel22.setText("Codigo Mascota");

        jLabel23.setText("Codigo Plan");

        jTextField_pago_codMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pago_codMascotaActionPerformed(evt);
            }
        });

        Crear_pago.setText("Crear Pago");
        Crear_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_pagoActionPerformed(evt);
            }
        });

        Modificar_pago.setText("Modificar Pago");
        Modificar_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_pagoActionPerformed(evt);
            }
        });

        Eliminar_pago.setText("Eliminar Pago");
        Eliminar_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_pagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCodigo_pago, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                            .addComponent(jTextField1Abono)
                            .addComponent(jTextFieldSaldo)
                            .addComponent(jTextFieldCtd_cuotas)
                            .addComponent(jTextFieldFecha_pago)
                            .addComponent(jTextFieldAfiliacion)
                            .addComponent(jTextField_pago_codMascota)
                            .addComponent(jTextField_pago_codPlan)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(Crear_pago)
                                .addGap(43, 43, 43)
                                .addComponent(Modificar_pago))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(Eliminar_pago)))))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldCodigo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField1Abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldCtd_cuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextFieldFecha_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22))
                    .addComponent(jTextField_pago_codMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_pago_codPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crear_pago)
                    .addComponent(Modificar_pago))
                .addGap(27, 27, 27)
                .addComponent(Eliminar_pago)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edicion Pago", jPanel7);

        jTablePago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTablePago);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Lista Pago", jPanel8);

        javax.swing.GroupLayout jPanelReporteLayout = new javax.swing.GroupLayout(jPanelReporte);
        jPanelReporte.setLayout(jPanelReporteLayout);
        jPanelReporteLayout.setHorizontalGroup(
            jPanelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        jPanelReporteLayout.setVerticalGroup(
            jPanelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reporte Cantidad de Mascotas", jPanelReporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdentificacionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificacionClienteActionPerformed

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jButtonCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearClienteActionPerformed
        // TODO add your handling code here:
        try {
            String nombreCliente = jTextFieldNombre.getText();
            String apellidosCliente = jTextFieldApellidos.getText();
            String identificacionCliente = jTextFieldIdentificacionCliente.getText();
            String direccionCliente = jTextFieldDireccion.getText();
            String telefonoCliente = jTextFieldTelefono.getText();
            Cliente cliente = new Cliente(identificacionCliente, nombreCliente, apellidosCliente, direccionCliente, telefonoCliente);
            CtlCliente controladorCliente = new CtlCliente();
            String respuesta = controladorCliente.CrearCliente(cliente);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaCliente();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_jButtonCrearClienteActionPerformed

    private void jButtonModificarCienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCienteActionPerformed
        // TODO add your handling code here:

        try {
            String nombreCliente = jTextFieldNombre.getText();
            String apellidosCliente = jTextFieldApellidos.getText();
            String identificacionCliente = jTextFieldIdentificacionCliente.getText();
            String direccionCliente = jTextFieldDireccion.getText();
            String telefonoCliente = jTextFieldTelefono.getText();

            Cliente cliente = new Cliente(identificacionCliente, nombreCliente, apellidosCliente, direccionCliente, telefonoCliente);
            CtlCliente controladorCliente = new CtlCliente();
            String respuesta = controladorCliente.ModificarCliente(cliente);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaCliente();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }

    }//GEN-LAST:event_jButtonModificarCienteActionPerformed

    private void jButtonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarClienteActionPerformed
        try {
            String identificacion_cliente = jTextFieldIdentificacionCliente.getText();
            CtlCliente controladorCliente = new CtlCliente();
            String respuesta = controladorCliente.EliminarCliente(identificacion_cliente);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaCliente();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }

    }//GEN-LAST:event_jButtonEliminarClienteActionPerformed

    private void Crear_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_mascotaActionPerformed
        try {
            int codigoMascota = Integer.parseInt(jTextFieldCodigo_mascota.getText());
            int edadMascota = Integer.parseInt(jTextFieldEdad_Mascota.getText());
            String especie = jTextFieldEspecie.getText();
            String identificacionCliente = jTextField_mascota_Identificacion_Cliente.getText();
            String nombreMascota = jTextFieldNombre_Mascota.getText();
            double pesoMascota = Double.parseDouble(jTextFieldPeso_Mascota.getText());
            Mascota mascota = new Mascota(codigoMascota, nombreMascota, edadMascota, pesoMascota, especie, identificacionCliente);
            CtlMascota controladorMascota = new CtlMascota();
            String respuesta = controladorMascota.CrearMascota(mascota);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaMascota();
            this.actualizarReporte();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_Crear_mascotaActionPerformed

    private void jTextFieldCodigo_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigo_mascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigo_mascotaActionPerformed

    private void jTextFieldNombre_MascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombre_MascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombre_MascotaActionPerformed

    private void jTextFieldDescripcion_planActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcion_planActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcion_planActionPerformed

    private void jTextField_pago_codMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pago_codMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pago_codMascotaActionPerformed

    private void Btt_Eliminar_MascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_Eliminar_MascotaActionPerformed
        try {
            int codigo_mascota = Integer.parseInt(jTextFieldCodigo_mascota.getText());
            CtlMascota controladorMascota = new CtlMascota();
            String respuesta = controladorMascota.EliminarMascota(codigo_mascota);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaMascota();
            this.actualizarReporte();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_Btt_Eliminar_MascotaActionPerformed

    private void modificar_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_mascotaActionPerformed
        try {
            int codigoMascota = Integer.parseInt(jTextFieldCodigo_mascota.getText());
            int edadMascota = Integer.parseInt(jTextFieldEdad_Mascota.getText());
            String especie = jTextFieldEspecie.getText();
            String identificacionCliente = jTextField_mascota_Identificacion_Cliente.getText();
            String nombreMascota = jTextFieldNombre_Mascota.getText();
            double pesoMascota = Double.parseDouble(jTextFieldPeso_Mascota.getText());
            Mascota mascota = new Mascota(codigoMascota, nombreMascota, edadMascota, pesoMascota, especie, identificacionCliente);
            CtlMascota controladorMascota = new CtlMascota();
            String respuesta = controladorMascota.ModificarMascota(mascota);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaMascota();
            this.actualizarReporte();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_modificar_mascotaActionPerformed

    private void Crear_PlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_PlanActionPerformed
        try {
            int codigoPlan = Integer.parseInt(jTextFieldCodigo_plan.getText());
            String descripcion = jTextFieldDescripcion_plan.getText();
            String nombre_plan = jTextFieldNombre_plan.getText();
            double precio = Double.parseDouble(jTextFieldPrecio_plan.getText());

            Plan plan = new Plan(codigoPlan, nombre_plan, descripcion, precio);
            CtlPlan controladorPlan = new CtlPlan();
            String respuesta = controladorPlan.CrearPlan(plan);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaPlan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_Crear_PlanActionPerformed

    private void Modificar_PlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_PlanActionPerformed
        try {
            int codigoPlan = Integer.parseInt(jTextFieldCodigo_plan.getText());
            String descripcion = jTextFieldDescripcion_plan.getText();
            String nombre_plan = jTextFieldNombre_plan.getText();
            double precio = Double.parseDouble(jTextFieldPrecio_plan.getText());

            Plan plan = new Plan(codigoPlan, nombre_plan, descripcion, precio);
            CtlPlan controladorPlan = new CtlPlan();
            String respuesta = controladorPlan.ModificarPlan(plan);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaPlan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_Modificar_PlanActionPerformed

    private void Eliminar_PlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_PlanActionPerformed
        try {
            int codigo_plan = Integer.parseInt(jTextFieldCodigo_plan.getText());
            CtlPlan controladorPlan = new CtlPlan();
            String respuesta = controladorPlan.EliminarPlan(codigo_plan);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaPlan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_Eliminar_PlanActionPerformed

    private void Crear_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_pagoActionPerformed
        try {
            int codigoPago = Integer.parseInt(jTextFieldCodigo_pago.getText());
            double abono = Double.parseDouble(jTextField1Abono.getText());
            int ctd_cuotas = Integer.parseInt(jTextFieldCtd_cuotas.getText());
            String fecha_pago = jTextFieldFecha_pago.getText();
            String plan_afiliacion = jTextFieldAfiliacion.getText();
            double saldo = Double.parseDouble(jTextFieldSaldo.getText());
            int codigoMascota = Integer.parseInt(jTextField_pago_codMascota.getText());
            int codigoPlan = Integer.parseInt(jTextField_pago_codPlan.getText());

            Pago pago = new Pago(codigoPago, abono, saldo, ctd_cuotas, fecha_pago, plan_afiliacion, codigoMascota, codigoPlan);
            CtlPago controladorPago = new CtlPago();
            String respuesta = controladorPago.CrearPago(pago);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaPago();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_Crear_pagoActionPerformed

    private void Modificar_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_pagoActionPerformed
        try {
            int codigoPago = Integer.parseInt(jTextFieldCodigo_pago.getText());
            double abono = Double.parseDouble(jTextField1Abono.getText());
            int ctd_cuotas = Integer.parseInt(jTextFieldCtd_cuotas.getText());
            String fecha_pago = jTextFieldFecha_pago.getText();
            String plan_afiliacion = jTextFieldAfiliacion.getText();
            double saldo = Double.parseDouble(jTextFieldSaldo.getText());
            int codigoMascota = Integer.parseInt(jTextField_pago_codMascota.getText());
            int codigoPlan = Integer.parseInt(jTextField_pago_codPlan.getText());

            Pago pago = new Pago(codigoPago, abono, saldo, ctd_cuotas, fecha_pago, plan_afiliacion, codigoMascota, codigoPlan);
            CtlPago controladorPago = new CtlPago();
            String respuesta = controladorPago.ModificarPago(pago);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaPago();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_Modificar_pagoActionPerformed

    private void Eliminar_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_pagoActionPerformed
        try {
            int codigo_pago = Integer.parseInt(jTextFieldCodigo_pago.getText());
            CtlPago controladorPago = new CtlPago();
            String respuesta = controladorPago.EliminarPago(codigo_pago);
            JOptionPane.showMessageDialog(rootPane, respuesta);
            this.ActualizarListaPago();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verifique los campos ingresados");
        }
    }//GEN-LAST:event_Eliminar_pagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    public void ActualizarListaCliente() {
        try {
            // Actualizar cliente
            CtlCliente controladorCliente = new CtlCliente();
            ArrayList<Cliente> clientes = controladorCliente.ConsultarCliente();
            DefaultTableModel modeloCliente = new DefaultTableModel();
            modeloCliente.addColumn("Identificacion cliente");
            modeloCliente.addColumn("Nombre");
            modeloCliente.addColumn("Apellidos");
            modeloCliente.addColumn("Direccion");
            modeloCliente.addColumn("Telefono");
            Object[] datoCliente = new Object[5];
            for (Cliente cliente : clientes) {
                datoCliente[0] = cliente.getIdentificacion_cliente();
                datoCliente[1] = cliente.getNombre();
                datoCliente[2] = cliente.getApellidos();
                datoCliente[3] = cliente.getDireccion();
                datoCliente[4] = cliente.getTelefono();
                modeloCliente.addRow(datoCliente);
            }
            jTableClientes.setModel(modeloCliente);

        } catch (Exception e) {
        }
    }

    public void ActualizarListaMascota() {
        try {

            // Actualizar mascota          
            CtlMascota controladorMascota = new CtlMascota();
            ArrayList<Mascota> mascotas = controladorMascota.ConsultarMascota();
            DefaultTableModel modeloMascota = new DefaultTableModel();
            modeloMascota.addColumn("Codigo mascota");
            modeloMascota.addColumn("Nombre mascota");
            modeloMascota.addColumn("Edad");
            modeloMascota.addColumn("Especie");
            modeloMascota.addColumn("Peso");
            modeloMascota.addColumn("Identificacion Cliente");
            Object[] datoMascota = new Object[6];
            for (Mascota mascota : mascotas) {
                datoMascota[0] = mascota.getCodigo_mascota();
                datoMascota[1] = mascota.getNombre_mascota();
                datoMascota[2] = mascota.getEdad();
                datoMascota[3] = mascota.getEspecie();
                datoMascota[4] = mascota.getPeso();
                datoMascota[5] = mascota.getIdentificacion_cliente();
                modeloMascota.addRow(datoMascota);
            }
            jTableMascota.setModel(modeloMascota);

        } catch (Exception e) {
        }
    }

    public void ActualizarListaPlan() {
        try {

            // Actualizar plan          
            CtlPlan controladorPlan = new CtlPlan();
            ArrayList<Plan> planes = controladorPlan.ConsultarPlanes();
            DefaultTableModel modeloPlan = new DefaultTableModel();
            modeloPlan.addColumn("Codigo plan");
            modeloPlan.addColumn("Nombre Plan");
            modeloPlan.addColumn("Precio");
            modeloPlan.addColumn("Descripcion");

            Object[] datoPlan = new Object[4];
            for (Plan plan : planes) {
                datoPlan[0] = plan.getCodigo_plan();
                datoPlan[1] = plan.getNombre_plan();
                datoPlan[2] = plan.getPrecio();
                datoPlan[3] = plan.getDescripcion();

                modeloPlan.addRow(datoPlan);
            }
            jTablePlan.setModel(modeloPlan);

        } catch (Exception e) {
        }
    }

    public void ActualizarListaPago() {
        try {

            // Actualizar pagos         
            CtlPago controladorPago = new CtlPago();
            ArrayList<Pago> pagos = controladorPago.ConsultarPagos();
            DefaultTableModel modeloPago = new DefaultTableModel();
            modeloPago.addColumn("Codigo pago");
            modeloPago.addColumn("Abono");
            modeloPago.addColumn("Cantidad de Cuotas");
            modeloPago.addColumn("Fecha de Pago");
            modeloPago.addColumn("Plan Afiliacion");
            modeloPago.addColumn("Saldo");
            modeloPago.addColumn("Codigo Mascota");
            modeloPago.addColumn("Codigo Plan");

            Object[] datoPago = new Object[8];
            for (Pago pago : pagos) {
                datoPago[0] = pago.getCodigo_pago();
                datoPago[1] = pago.getAbono();
                datoPago[2] = pago.getCtd_cuotas();
                datoPago[3] = pago.getFecha_pago();
                datoPago[4] = pago.getPlan_afiliacion();
                datoPago[5] = pago.getSaldo();
                datoPago[6] = pago.getCodigo_mascota();
                datoPago[7] = pago.getCodigo_plan();

                modeloPago.addRow(datoPago);
            }
            jTablePago.setModel(modeloPago);

        } catch (Exception e) {
        }
    }
    
        public void actualizarReporte(){
        CtlCliente controladorCliente = new CtlCliente();
        ArrayList<Cantidad_Mascotas_Por_Cliente> reporteNumMascotas = controladorCliente.ArrayCantidadMascotas();
        DefaultPieDataset dataset = new DefaultPieDataset();
        for (Cantidad_Mascotas_Por_Cliente reporteCliente : reporteNumMascotas) {
            dataset.setValue(reporteCliente.getNombreCliente(), reporteCliente.getCantidadMacotas());
        }
        JFreeChart chart = ChartFactory.createPieChart("Mascotas por Cliente", dataset, true, true, Locale.ITALY);
        ChartPanel panel = new ChartPanel(chart);
        panel.setMouseWheelEnabled(true);
        jPanelReporte.setLayout(new java.awt.BorderLayout());
        jPanelReporte.add(panel,BorderLayout.CENTER);
        jPanelReporte.validate();
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btt_Eliminar_Mascota;
    private javax.swing.JButton Crear_Plan;
    private javax.swing.JButton Crear_mascota;
    private javax.swing.JButton Crear_pago;
    private javax.swing.JButton Eliminar_Plan;
    private javax.swing.JButton Eliminar_pago;
    private javax.swing.JButton Modificar_Plan;
    private javax.swing.JButton Modificar_pago;
    private javax.swing.JButton jButtonCrearCliente;
    private javax.swing.JButton jButtonEliminarCliente;
    private javax.swing.JButton jButtonModificarCiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableMascota;
    private javax.swing.JTable jTablePago;
    private javax.swing.JTable jTablePlan;
    private javax.swing.JTextField jTextField1Abono;
    private javax.swing.JTextField jTextFieldAfiliacion;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCodigo_mascota;
    private javax.swing.JTextField jTextFieldCodigo_pago;
    private javax.swing.JTextField jTextFieldCodigo_plan;
    private javax.swing.JTextField jTextFieldCtd_cuotas;
    private javax.swing.JTextField jTextFieldDescripcion_plan;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEdad_Mascota;
    private javax.swing.JTextField jTextFieldEspecie;
    private javax.swing.JTextField jTextFieldFecha_pago;
    private javax.swing.JTextField jTextFieldIdentificacionCliente;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre_Mascota;
    private javax.swing.JTextField jTextFieldNombre_plan;
    private javax.swing.JTextField jTextFieldPeso_Mascota;
    private javax.swing.JTextField jTextFieldPrecio_plan;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextField_mascota_Identificacion_Cliente;
    private javax.swing.JTextField jTextField_pago_codMascota;
    private javax.swing.JTextField jTextField_pago_codPlan;
    private javax.swing.JButton modificar_mascota;
    // End of variables declaration//GEN-END:variables
}
